
FROM docker.io/node:24-alpine

ENV TZ="Europe/Helsinki"

WORKDIR /opt/app-root/src

ARG CI
ENV CI=$CI

COPY package* ./
RUN npm ci
COPY . .

EXPOSE 3000

# CMD ["npx", "serve", "-s", "build"]
CMD ["npm", "run", "dev"]
