
FROM docker.io/node:24-alpine

ENV TZ="Europe/Helsinki"

WORKDIR /opt/app-root/src

ARG CI
ENV CI=$CI

COPY package* ./
RUN npm ci
COPY . .

RUN npm run build

EXPOSE 3001

CMD ["npx", "serve", "-s", "build"]
